<?php

namespace Rice\DeckKeeperBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardSetRepository extends EntityRepository
{
}
